# Generated by Django 4.2.23 on 2025-09-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name_activities', models.CharField(max_length=100)),
                ('day_activities', models.CharField(blank=True, default='', max_length=20)),
                ('start_time_activities', models.TimeField()),
                ('stop_time_activities', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name_pre', models.CharField(max_length=100)),
                ('subject_code_pre', models.CharField(max_length=20)),
                ('subject_name_pre', models.CharField(max_length=100)),
                ('curriculum_type_pre', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type_pre', models.CharField(blank=True, default='', max_length=50)),
                ('type_pre', models.CharField(max_length=20)),
                ('hours_pre', models.IntegerField(default=0)),
                ('day_pre', models.CharField(blank=True, default='', max_length=20)),
                ('start_time_pre', models.TimeField()),
                ('stop_time_pre', models.TimeField()),
                ('room_name_pre', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Code', models.CharField(max_length=50)),
                ('Subject_Name', models.CharField(blank=True, default='', max_length=100)),
                ('Teacher', models.CharField(blank=True, default='', max_length=100)),
                ('Room', models.CharField(blank=True, default='', max_length=50)),
                ('Room_Type', models.CharField(blank=True, default='', max_length=50)),
                ('Type', models.CharField(blank=True, default='', max_length=20)),
                ('Curriculum_Type', models.CharField(blank=True, default='', max_length=20)),
                ('Day', models.CharField(blank=True, default='', max_length=20)),
                ('Hour', models.IntegerField(default=0)),
                ('Time_Slot', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['Day', 'Hour', 'Course_Code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name_teacher', models.CharField(max_length=100)),
                ('subject_code_teacher', models.CharField(max_length=20)),
                ('subject_name_teacher', models.CharField(max_length=100)),
                ('curriculum_type_teacher', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type_teacher', models.CharField(blank=True, max_length=50)),
                ('section_teacher', models.CharField(max_length=10)),
                ('theory_slot_amount_teacher', models.IntegerField(default=0)),
                ('lab_slot_amount_teacher', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Timedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('stop_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'จันทร์'), ('Tue', 'อังคาร'), ('Wed', 'พุธ'), ('Thu', 'พฤหัสบดี'), ('Fri', 'ศุกร์'), ('Sat', 'เสาร์'), ('Sun', 'อาทิตย์')], max_length=3)),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('day_of_week', 'start_time', 'stop_time')},
            },
        ),
        migrations.CreateModel(
            name='WeekActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='scheduler.timeslot')),
            ],
            options={
                'ordering': ['slot__day_of_week', 'slot__start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_groups', to='scheduler.grouptype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='scheduler.roomtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupAllow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_slots', to='scheduler.grouptype')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_type_allows', to='scheduler.timeslot')),
            ],
            options={
                'ordering': ['group_type__name', 'slot__day_of_week', 'slot__start_time'],
                'unique_together': {('group_type', 'slot')},
            },
        ),
    ]
