# Generated by Django 4.2.23 on 2025-08-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name_activities', models.CharField(max_length=100)),
                ('day_activities', models.CharField(blank=True, default='', max_length=20)),
                ('start_time_activities', models.TimeField()),
                ('stop_time_activities', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name_pre', models.CharField(max_length=100)),
                ('subject_code_pre', models.CharField(max_length=20)),
                ('subject_name_pre', models.CharField(max_length=100)),
                ('curriculum_type_pre', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type_pre', models.CharField(blank=True, default='', max_length=50)),
                ('type_pre', models.CharField(max_length=20)),
                ('hours_pre', models.IntegerField(default=0)),
                ('day_pre', models.CharField(blank=True, default='', max_length=20)),
                ('start_time_pre', models.TimeField()),
                ('stop_time_pre', models.TimeField()),
                ('room_name_pre', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name_room', models.CharField(max_length=50)),
                ('room_type_room', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Code', models.CharField(max_length=50)),
                ('Subject_Name', models.CharField(blank=True, default='', max_length=100)),
                ('Teacher', models.CharField(blank=True, default='', max_length=100)),
                ('Room', models.CharField(blank=True, default='', max_length=50)),
                ('Room_Type', models.CharField(blank=True, default='', max_length=50)),
                ('Type', models.CharField(blank=True, default='', max_length=20)),
                ('Curriculum_Type', models.CharField(blank=True, default='', max_length=20)),
                ('Day', models.CharField(blank=True, default='', max_length=20)),
                ('Hour', models.IntegerField(default=0)),
                ('Time_Slot', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['Day', 'Hour', 'Course_Code'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_group', models.CharField(max_length=100)),
                ('subject_code_stu', models.CharField(max_length=20)),
                ('curriculum_type_stu', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name_teacher', models.CharField(max_length=100)),
                ('subject_code_teacher', models.CharField(max_length=20)),
                ('subject_name_teacher', models.CharField(max_length=100)),
                ('curriculum_type_teacher', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type_teacher', models.CharField(blank=True, max_length=50)),
                ('section_teacher', models.CharField(max_length=10)),
                ('theory_slot_amount_teacher', models.IntegerField(default=0)),
                ('lab_slot_amount_teacher', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Timedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('stop_time', models.CharField(max_length=20)),
            ],
        ),
    ]
