# Generated by Django 4.2.23 on 2025-09-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name_course', models.CharField(max_length=100)),
                ('subject_code_course', models.CharField(max_length=20)),
                ('subject_name_course', models.CharField(max_length=100)),
                ('curriculum_type_course', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type_course', models.CharField(blank=True, default='', max_length=50)),
                ('section_course', models.CharField(max_length=10)),
                ('theory_slot_amount_course', models.IntegerField(default=0)),
                ('lab_slot_amount_course', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherSchedule',
        ),
    ]
