# Generated by Django 4.2.23 on 2025-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_courseschedule_delete_teacherschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivitySchedule',
        ),
        migrations.AlterModelOptions(
            name='weekactivity',
            options={},
        ),
        migrations.RemoveField(
            model_name='weekactivity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weekactivity',
            name='slot',
        ),
        migrations.AddField(
            model_name='weekactivity',
            name='act_name_activity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='weekactivity',
            name='day_activity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='weekactivity',
            name='start_time_activity',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weekactivity',
            name='stop_time_activity',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
